//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public Location()
        {
            this.Photo = new HashSet<Photo>();
        }
    
        public int LocationId { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string District { get; set; }
    
        public virtual ICollection<Photo> Photo { get; set; }
    }
}
