//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Privilege
    {
        public int PrivilegeId { get; set; }
        public short PrivilegeMaster { get; set; }
        public string PrivilegeMasterValue { get; set; }
        public short PrivilegeAccess { get; set; }
        public int PrivilegeAccessValue { get; set; }
        public short PrivilegeOperation { get; set; }
    }
}
